site:
  title: C2PA Specifications
  url: https://c2pa.org/specifications
  # start_page: specifications::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    tags: [2.0, 1.4, 1.3, 1.2, 1.1, 1.0]
    start_path: docs
  - url: ./../specs-core
    branches: [antora-*]
    # branches: HEAD
    # tags: [2.0, 1.4, 1.3, 1.2, 1.1, 1.0]
    start_path: docs
  - url: ./../attestations
    branches: HEAD
    # tags: [1.4]
    start_path: docs
  - url: ./../threats-harms
    branches: [antora-*]
    start_path: docs
  - url: ./../ux
    branches: [antora-*]
    start_path: docs
  - url: ./../documentation
    branches: [antora-*]
    start_path: docs
ui:
  bundle:
    url: ./../c2pa-docs-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
asciidoc:
  extensions:
  - asciidoctor-kroki
