site:
  title: C2PA Specifications
  url: https://c2pa.org/specifications
  start_page: specifications::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: docs
  - url: ./../specs-core
    branches: [1.0, HEAD]
    start_path: docs
  - url: ./../threats-harms
    branches: HEAD
    start_path: docs
  - url: ./../ux
    branches: HEAD
    start_path: docs
  - url: ./../documentation
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: ./../c2pa-docs-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
asciidoc:
  extensions:
  - asciidoctor-kroki
