site:
  title: C2PA Specifications
  url: https://c2pa.org/specifications
  start_page: index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: content
ui:
  bundle:
#    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
#    url: https://github.com/asciidoctor/asciidoctor-docs-ui/releases/download/prod-267/ui-bundle.zip
    url: ./../c2pa-docs-ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files: [ .nojekyll ]
  - path: .nojekyll
asciidoc:
  extensions:
  - asciidoctor-kroki
